Enable scaling reserved RAM on GHES
github/codeql-action pull request #1866
Opened 2023-09-05 11:21 UTC by henrymercer

We have completed our experiments with scaling reserved RAM and this feature is now ready to roll out to GHES.

This PR also adds an environment variable `CODEQL_ACTION_SCALING_RESERVED_RAM_PERCENTAGE` we can use to customize the percentage of scaling reserved RAM going forward.  This gives us a more flexible way of opting out of scaling RAM once we deprecate the feature flag by giving us a mechanism that also lets us adjust the RAM calculation.

### Merge / deployment checklist

- [x] Confirm this change is backwards compatible with existing workflows.
- [x] Confirm the [readme](https://github.com/github/codeql-action/blob/main/README.md) has been updated if necessary.
- [x] Confirm the [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) has been updated if necessary.

2023-09-06 21:33 UTC, angelapwen requested changes
Looks good, just a comment about fixing up the changelog note!

2023-09-06 21:33 UTC, angelapwen commented on CHANGELOG.md
> +- Improve the calculation of default amount of RAM used for query execution on GitHub Enterprise Server. This now reduces in proportion to the runner's total memory to better account for system memor
PR number should be #1866 😄

2023-09-07 10:18 UTC, henrymercer commented on CHANGELOG.md
> +- Improve the calculation of default amount of RAM used for query execution on GitHub Enterprise Server. This now reduces in proportion to the runner's total memory to better account for system memor
Fixed in the last commit 👍

2023-09-07 18:32 UTC, angelapwen approved these changes

2023-09-07 18:38 UTC, merged