Spelling
github/codeql-action pull request #404
Opened 2021-02-28 08:16 UTC by jsoref

This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).

The misspellings have been reported at https://github.com/jsoref/codeql-action/commit/525c790ab88928c92ff49e731f998468d1ed0e13#commitcomment-47650569

The action reports that the changes in this PR would make it happy: https://github.com/jsoref/codeql-action/commit/42808dbc96d5279ddc197dd9812f29cda3605e6f

Note: this PR does not include the action. If you're interested in running a spell check on every PR and push, that can be offered separately.

### Merge / deployment checklist

- [ ] Confirm this change is backwards compatible with existing workflows.
- [ ] Confirm the [readme](https://github.com/github/codeql-action/blob/master/README.md) has been updated if necessary.

2021-02-28 08:19 UTC, jsoref commented on lib/analysis-paths.js
> +        logger.warning('The "paths"/"paths-ignore" fields of the config only have effect for JavaScript and Python');
This is a brand

2021-02-28 08:19 UTC, jsoref commented on lib/codeql.test.js
> +ava_1.default('download codeql bundle cache with pinned different version cached if "latest" tools specified', async (t) => {
I can understand this being intentional, I don't think it's a valuable spelling divergence.

2021-02-28 08:19 UTC, jsoref commented on lib/init.js
> +    // Setup tools on the GitHub hosted runners
This is a brand

2021-02-28 08:19 UTC, jsoref commented on lib/util.js
> +function parseGitHubUrl(inputUrl) {
This is clearly an API, but if it's an internal API, then it's worth changing.

If it's from an upstream library, I'd be more than happy to try to get it changed.

I can also easily drop the API change from the general brand change -- just let me know.

2021-02-28 08:19 UTC, jsoref commented on src/sarif_v2.1.0_schema.json
> +          "description": "A stable, unique identifier for this external properties object, in the form of a GUID.",
This is a versioned schema. I can't tell if there's an upstream for this. If there is, let me know and I can try to send the fix to it instead.

Possibly https://github.com/oasis-tcs/sarif-spec ?

2021-03-01 02:39 UTC, aeisenberg requested changes
Thanks for submitting your PR! Most of your changes look reasonable.

You need to re-run `npm run build` in order to get all the compiled javascript corrected. Also, see my comment about removing the changes to the sarif spec file.

2021-03-01 02:39 UTC, aeisenberg commented on src/sarif_v2.1.0_schema.json
> +          "description": "A stable, unique identifier for this external properties object, in the form of a GUID.",
Yes, this typo is also in the original schema itself. 
https://github.com/oasis-tcs/sarif-spec/blob/master/Schemata/sarif-schema-2.1.0.json#L600

It's a non-functional change, but best to leave this file unchanged just in case. If you're feeling motivated, I'm sure a PR in the `sarif-spec` repo would be appreciated.

2021-03-01 02:52 UTC, jsoref commented
@aeisenberg: yeah, I've already made the PR to them; dropped here. Updated the map.

I also have a set on en_US changes which I imagined might be controversial, so I left them out of this PR.
https://github.com/jsoref/codeql-action/compare/spelling...en-us

This repository appears to have a mix of en_US/en_GB. I generally encourage repositories to use only one flavor of English... I can offer a PR to adopt either flavor.

2021-03-01 17:50 UTC, aeisenberg commented
Failing build checks are unrelated to this change and are fixed in main.

2021-03-01 18:32 UTC, aeisenberg commented
> This repository appears to have a mix of en_US/en_GB. I generally encourage repositories to use only one flavor of English... I can offer a PR to adopt either flavor.

I don't think we have a policy on this. Feel free to open a separate PR and we can discuss.

2021-03-01 18:33 UTC, aeisenberg approved these changes

2021-03-18 16:10 UTC, aeisenberg commented
Rebased and squashed.

2021-03-18 16:40 UTC, merged