[WIP] Add the `isAction` function
github/codeql-action pull request #516
Opened 2021-05-20 22:21 UTC by aeisenberg

This commit changes the way the action determines if running in action
or runner mode. There is now an environment variable that is set at the
beginning of the process and elsewhere in the process, we can check to
see if the variable is set.

It's not quite ready for review since I need to add some more tests.

### Merge / deployment checklist

- [ ] Confirm this change is backwards compatible with existing workflows.
- [ ] Confirm the [readme](https://github.com/github/codeql-action/blob/main/README.md) has been updated if necessary.
- [ ] Confirm the [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) has been updated if necessary.

2021-05-21 21:19 UTC, adityasharad reviewed
Neat! I defer to Robert on whether the mode initialisations are in the right place, but the logic looks sensible to me.

2021-05-21 21:19 UTC, adityasharad commented on src/api-client.ts
> +      userAgent: `CodeQL ${getMode()} ${pkg.version}`,
I believe this is the convention and follows the HTTP spec.
```suggestion
      userAgent: `CodeQL-${getMode()}/${pkg.version}`,
```

2021-05-22 19:37 UTC, RA80533 requested changes

2021-05-22 19:37 UTC, RA80533 commented on src/actions-util.ts
> +  return mode;
Be very careful about using type assertions. When used to mark sources of input as valid, it can potentially lead to untrusted data being allowed in places it shouldn't. While that's not the case here because the input is validated, it warrants a note considering that this snippet is quite close to something CodeQL would flag.

Instead of a type assertion, allow `mode` to settle to whatever type the compiler infers it to be (in this case, it would be inferred to be a `string`). The conditional block underneath its assignment provides enough information to the TypeScript compiler for it to correctly infer `mode` to be of type `Mode` when it's returned on line 751.

2021-05-22 19:40 UTC, RA80533 commented on src/actions-util.ts
> +  const mode = getRequiredEnvParam(CODEQL_RUN_MODE_ENV_VAR) as Mode;
```suggestion
  const mode = getRequiredEnvParam(CODEQL_RUN_MODE_ENV_VAR);
```

2021-05-23 14:47 UTC, aeisenberg commented on src/actions-util.ts
> +  const mode = getRequiredEnvParam(CODEQL_RUN_MODE_ENV_VAR) as Mode;
Yes. This type assertion is not necessary. Thanks.

2021-05-23 14:47 UTC, aeisenberg commented on src/actions-util.ts
> +  return mode;
Good point.

2021-05-26 23:20 UTC, RA80533 commented
The conditional branching within the updated getCodeQLBundleDownloadURL function should be tested based on the new method of determining the mode. Every occurrence in which an explicit mode was passed in now implicitly relies upon the environment in which it is called.

Should that implicit behavior be moved to a higher level of abstraction, e.g., into functions directly consumed by the end-user? There are a lot of lower-level functions reliant upon the results from getCodeQLBundleDownloadURL.

2021-05-27 23:10 UTC, aeisenberg commented
Thanks for the comment @RA80533. I added a couple of more unit tests. I feel like the code is reasonably safe now. We are sure to set the mode at the beginning of every entry point. If there is a call to get the mode and it hasn't been set yet, then that will fail.

In some ways, the logic is more complex because some low level functions now rely on a new environment variable, but the trade off is that we no longer need to pass the `mode` parameter around. I had originally tried keeping the `mode` parameter and passing it around, but then almost every function needed access to it. Using the environment variable in a single place seems like a reasonable trade-off. There are other parts of the code that also rely on environment variables, so this situation is not too different.

2021-05-27 23:34 UTC, RA80533 commented
> In some ways, the logic is more complex because some low level functions now rely on a new environment variable, but the trade off is that we no longer need to pass the `mode` parameter around. I had originally tried keeping the `mode` parameter and passing it around, but then almost every function needed access to it. Using the environment variable in a single place seems like a reasonable trade-off. There are other parts of the code that also rely on environment variables, so this situation is not too different.

It is very much a case of deciding which to trade off. Environment variables become unwieldy in larger projects because they create a mathematical side effect in the flow of logic; for smaller projects, such as this one, the flow of data is easy enough to follow to the point that such dependent behavior is easy to track down.

/lgtm

2021-05-28 18:55 UTC, aeisenberg commented
Ooooh...code scanning found a bug. Thank you code scanning.

2021-05-28 19:23 UTC, aeisenberg commented on src/actions-util.ts
> +    core.exportVariable(CODEQL_RUN_MODE_ENV_VAR, mode);
Note this is a code scanning error, but a false positive. We cannot have a code path accessible from the runner that will call into the core library. The if clause above prevents this from happening.

2021-05-28 20:02 UTC, aeisenberg commented
Updated ql queries that look for runner/actions access. Could I get another look at this?

2021-05-28 20:08 UTC, RA80533 commented
Without the guard, what would be available to non-Actions runners through the core library?

2021-05-28 20:40 UTC, aeisenberg commented
Yes, mostly right...there are _some_ actions libraries that are ok to use for the runner. https://github.com/github/codeql-action/blob/3a474e8ed612f1b0ae2ff3b2586171b7ea29a6fc/queries/unguarded-action-lib.ql#L16-L21

2021-05-29 00:59 UTC, adityasharad approved these changes
Nice. Logic makes sense and neat adjustment to the query; a few minor suggestions there.

There's probably room to combine more of the logic in that query, and use some builtin features of the CodeQL JS libraries, but we can do that separately. No need to hold up this PR.

2021-05-29 00:59 UTC, adityasharad commented on queries/unguarded-action-lib.ql
> +  abstract Expr getAnActionsExpr();
You could instead declare:
```ql
abstract Stmt getActionsBlock();

/**
  * Gets an expr that is only executed on actions
 */
final Expr getAnActionsExpr() { getActionsBlock().getAChildStmt*().getAChildExpr*() = result }
```

This way each subclass needs to describe what they consider an Actions-specific statement, and you don't need to repeat the logic for an Actions-specific expression.

2021-05-31 16:31 UTC, aeisenberg commented on queries/unguarded-action-lib.ql
> +  abstract Expr getAnActionsExpr();
Yes. That's better. Thanks.

2021-05-31 16:33 UTC, aeisenberg commented on src/runner.ts
> +    setMode(Mode.runner);
Hmmm...it looks like there is an event mechanism for `commander`, but it's not quite what we need and it is internal, so I think we will need to create a query here.

2021-05-31 16:44 UTC, aeisenberg commented
Wait...commander v8 is soon to be released with a `hook` for `preAction` and `postAction` in it. I will get this merged, and then do the update for v8.

2021-05-31 16:49 UTC, merged