Suggest limiting push/pull_request triggers
github/codeql-action pull request #620
Opened 2021-07-15 16:20 UTC by rneatherway

Bring the template in line with the one used by the UI.

### Merge / deployment checklist

- [ ] Confirm this change is backwards compatible with existing workflows.
- [ ] Confirm the [readme](https://github.com/github/codeql-action/blob/main/README.md) has been updated if necessary.
- [ ] Confirm the [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) has been updated if necessary.

2021-07-15 16:49 UTC, adityasharad requested changes

2021-07-15 16:49 UTC, adityasharad commented on README.md
> +  pull_request: [main]
```suggestion
  push:
    branches: [main]
  pull_request:
    branches: [main]
```

2021-07-16 09:12 UTC, edoardopirovano approved these changes
LGTM

2021-07-26 15:16 UTC, adityasharad approved these changes

2021-07-26 15:28 UTC, merged