Do not artificially restrict the set of supported languages
github/codeql-action pull request #779
Opened 2021-10-14 19:45 UTC by esbena

### Description

The hardcoded set of supported languages in `languages.ts` makes it hard to experiment with new languages as custom branch with a modified `languages.ts` is required for every new language. 

This PR makes it easier to experiment with new languages by making the `codeql-action` indifferent to the language choice, except for some *additional* support for known languages. 

### Implementation

The old implementation throws an early error if the user-provided language is not in the hardcoded set. As an alternative, a `Language` is now just a lowercase string, and an early error is only produced if that language is not in the output of `codeql resolve languages`.  The old `Language` enum is now named `KnownLanguage`, and is used in the places where *additional* support for a specific language is desired. 

This should be fully backwards compatible, as the implementation now should throw an early exception in fewer situations. This may be detrimental to how early and well users are informed of input mistakes. On the other hand, it is consistent with how the provided `codeql` and environment behave.

PMs may want to keep the tight coupling between the codeql-action and the GitHub-controlled CodeQL repositories, I do not.

### Testing

I will use this branch for some internal experiments for a short while. Hopefully, the many changes wont result in too many conflicts when we are ready to merge.

### Merge / deployment checklist

- [ ] Confirm this change is backwards compatible with existing workflows.
- [ ] Confirm the [readme](https://github.com/github/codeql-action/blob/main/README.md) has been updated if necessary.
- [ ] Confirm the [changelog](https://github.com/github/codeql-action/blob/main/CHANGELOG.md) has been updated if necessary.

2022-12-10 03:09 UTC, walid97t requested changes
go ahead

2023-03-17 22:41 UTC, tied2token approved these changes

2023-12-28 20:47 UTC, iamannalynleynes1206 approved these changes

2025-08-06 11:47 UTC, henrymercer commented
Done in https://github.com/github/codeql-action/pull/2914

2025-08-06 11:47 UTC, closed without merging